import 'package:drift/drift.dart';
import 'package:khmerbiz_pos/data/datasources/local/database.dart';
import 'package:uuid/uuid.dart';

part 'transactions_dao.g.dart';

/// A container for a [transaction] and its associated [items].
class TransactionWithItems {
  /// Creates a new [TransactionWithItems].
  TransactionWithItems({required this.transaction, required this.items});

  /// The transaction header record.
  final TransactionModel transaction;

  /// The list of items belonging to this transaction.
  final List<TransactionItemModel> items;
}

/// Represents the results of a daily sales summary.
class DailySummaryResult {
  /// Creates a new [DailySummaryResult].
  DailySummaryResult({
    required this.date,
    required this.totalTransactions,
    required this.totalRevenue,
    required this.totalRevenueUSD,
  });

  /// The date of the summary.
  final DateTime date;

  /// Total number of transactions completed on this date.
  final int totalTransactions;

  /// Total revenue in Khmer Riel (KHR).
  final double totalRevenue;

  /// Total revenue in US Dollars (USD).
  final double totalRevenueUSD;
}

/// Represents the results of a weekly sales summary.
class WeeklySummaryResult {
  /// Creates a new [WeeklySummaryResult].
  WeeklySummaryResult({
    required this.totalTransactions,
    required this.totalRevenue,
    required this.totalRevenueUSD,
  });

  /// Total number of transactions completed during the week.
  final int totalTransactions;

  /// Total revenue in Khmer Riel (KHR).
  final double totalRevenue;

  /// Total revenue in US Dollars (USD).
  final double totalRevenueUSD;
}

/// Represents a product that is among the top sellers.
class TopProductResult {
  /// Creates a new [TopProductResult].
  TopProductResult({
    required this.productId,
    required this.quantitySold,
    required this.totalRevenue,
  });

  /// The unique identifier of the product.
  final String productId;

  /// The total quantity of the product sold.
  final double quantitySold;

  /// The total revenue generated by this product.
  final double totalRevenue;
}

/// Data Access Object for Transactions and related tables.
///
/// Handles complex sale processing, reporting, and voiding logic.
@DriftAccessor(
  tables: [
    Transactions,
    TransactionItems,
    Products,
    InventoryLogs,
    Customers,
    SyncQueue,
  ],
)
class TransactionsDao extends DatabaseAccessor<AppDatabase>
    with _$TransactionsDaoMixin {
  /// Creates a new [TransactionsDao] with the given [db].
  TransactionsDao(super.db);

  final Uuid _uuid = const Uuid();

  /// Processes a new completed [transaction] with its associated [items].
  ///
  /// This operation is performed within a single database transaction and:
  /// 1. Generates a unique receipt number.
  /// 2. Inserts the transaction header.
  /// 3. Inserts each item record.
  /// 4. Updates product stock levels.
  /// 5. Records inventory log entries.
  /// 6. Updates customer loyalty points/stats (if provided).
  /// 7. Adds a record to the sync queue.
  ///
  /// Returns the newly created transaction ID.
  Future<String> processSale({
    required TransactionsCompanion transaction,
    required List<TransactionItemsCompanion> items,
  }) async {
    return db.transaction<String>(() async {
      // a. Generate receiptNumber
      final now = DateTime.now();
      final todayStr =
          '${now.year}${now.month.toString().padLeft(2, '0')}${now.day.toString().padLeft(2, '0')}';
      final startOfDay = DateTime(now.year, now.month, now.day);
      final endOfDay = startOfDay.add(const Duration(days: 1));
      final todayCount = await (select(transactions)
            ..where(
              (tbl) => tbl.createdAt.isBetweenValues(startOfDay, endOfDay),
            ))
          .get()
          .then((l) => l.length);
      final sequence = (todayCount + 1).toString().padLeft(4, '0');
      final receiptNumber = 'TXN-$todayStr-$sequence';

      final txId = _uuid.v4();

      // b. Insert transactions record
      final txToInsert = transaction.copyWith(
        id: Value(txId),
        receiptNumber: Value(receiptNumber),
      );
      await into(transactions).insert(txToInsert);

      // c, d, e. Iterate items
      for (final item in items) {
        final itemId = _uuid.v4();
        await into(transactionItems).insert(
          item.copyWith(
            id: Value(itemId),
            transactionId: Value(txId),
          ),
        );

        // d. Update product stock (atomic decrement)
        final productId = item.productId.value;
        final qty = item.quantity.value;
        await customUpdate(
          'UPDATE products SET stock = stock - ? WHERE id = ?',
          variables: [Variable.withReal(qty), Variable.withString(productId)],
          updates: {products},
        );

        // Fetch new stock for the log (it gets tricky to do it without an extra read,
        // but since we just decremented, we can read the product or calculate before vs after)
        // Since we need exact 'before' and 'after' for InventoryLog:
        final p = await (select(products)
              ..where((tbl) => tbl.id.equals(productId)))
            .getSingle();
        final stockAfter = p.stock;
        final stockBefore =
            stockAfter + qty; // derive before stock based on delta

        // e. Insert inventory log
        await into(inventoryLogs).insert(
          InventoryLogsCompanion(
            id: Value(_uuid.v4()),
            productId: Value(productId),
            changeAmount: Value(-qty),
            stockBefore: Value(stockBefore),
            stockAfter: Value(stockAfter),
            reason: const Value('sale'),
            referenceId: Value(txId),
            staffId: transaction.staffId,
          ),
        );
      }

      // f. If customerId update loyalty
      if (transaction.customerId.present &&
          transaction.customerId.value != null) {
        final cId = transaction.customerId.value;
        final amount = transaction.totalAmount.value;
        await customUpdate(
          'UPDATE customers SET loyaltyPoints = loyaltyPoints + ?, totalSpent = totalSpent + ?, totalTransactions = totalTransactions + 1 WHERE id = ?',
          variables: [
            Variable.withReal(
                amount * 0.01,), // dummy logic 1 point per 100 spent
            Variable.withReal(amount),
            Variable.withString(cId!),
          ],
          updates: {customers},
        );
      }

      // g. Insert to sync_queue
      await into(syncQueue).insert(
        SyncQueueCompanion(
          id: Value(_uuid.v4()),
          operationType: const Value('create'),
          entityType: const Value('transaction'),
          entityId: Value(txId),
          payload:
              const Value(''), // This will be handled by the Repository layer
          priority: const Value(1),
          createdAt: Value(DateTime.now()),
        ),
      );

      return txId;
    });
  }

  /// Returns a reactive stream of transactions created today.
  Stream<List<TransactionModel>> watchTodayTransactions() {
    final now = DateTime.now();
    final start = DateTime(now.year, now.month, now.day);
    final end = start.add(const Duration(days: 1));
    return (select(transactions)
          ..where((tbl) => tbl.transactionDate.isBetweenValues(start, end))
          ..orderBy([(t) => OrderingTerm.desc(t.transactionDate)]))
        .watch();
  }

  /// Returns a reactive stream of transactions within a specific [start] and [end] date range.
  Stream<List<TransactionModel>> watchTransactionsByDateRange(
      DateTime start, DateTime end,) {
    return (select(transactions)
          ..where((tbl) => tbl.transactionDate.isBetweenValues(start, end))
          ..orderBy([(t) => OrderingTerm.desc(t.transactionDate)]))
        .watch();
  }

  /// Retrieves a transaction and all its line items by its [id].
  Future<TransactionWithItems?> getTransactionWithItems(String id) async {
    final tx = await (select(transactions)..where((tbl) => tbl.id.equals(id)))
        .getSingleOrNull();
    if (tx == null) return null;
    final items = await (select(transactionItems)
          ..where((tbl) => tbl.transactionId.equals(id)))
        .get();
    return TransactionWithItems(transaction: tx, items: items);
  }

  /// Aggregates a summary of sales for a specific [date].
  Future<DailySummaryResult> getDailySummary(DateTime date) async {
    final start = DateTime(date.year, date.month, date.day);
    final end = start.add(const Duration(days: 1));

    final txList = await (select(transactions)
          ..where((tbl) =>
              tbl.transactionDate.isBetweenValues(start, end) &
              tbl.status.equals('completed'),))
        .get();

    double rev = 0;
    double revUSD = 0;
    for (final tx in txList) {
      rev += tx.totalAmount;
      revUSD += tx.totalAmountUSD;
    }

    return DailySummaryResult(
      date: date,
      totalTransactions: txList.length,
      totalRevenue: rev,
      totalRevenueUSD: revUSD,
    );
  }

  /// Aggregates a summary of sales for a week starting from [weekStart].
  Future<WeeklySummaryResult> getWeeklySummary(DateTime weekStart) async {
    final start = DateTime(weekStart.year, weekStart.month, weekStart.day);
    final end = start.add(const Duration(days: 7));

    final txList = await (select(transactions)
          ..where((tbl) =>
              tbl.transactionDate.isBetweenValues(start, end) &
              tbl.status.equals('completed'),))
        .get();

    double rev = 0;
    double revUSD = 0;
    for (final tx in txList) {
      rev += tx.totalAmount;
      revUSD += tx.totalAmountUSD;
    }

    return WeeklySummaryResult(
      totalTransactions: txList.length,
      totalRevenue: rev,
      totalRevenueUSD: revUSD,
    );
  }

  /// Retrieves the top selling products within a date range.
  ///
  /// [start] and [end] define the time window. [limit] restricts the number of results.
  Future<List<TopProductResult>> getTopProducts(
      DateTime start, DateTime end, int limit,) async {
    // Basic implementation since drift custom queries require more complex setup:
    final query = customSelect(
      '''
      SELECT productId, SUM(quantity) as qty, SUM(subtotal) as rev
      FROM transaction_items
      INNER JOIN transactions ON transactions.id = transaction_items.transactionId
      WHERE transactions.transactionDate BETWEEN ? AND ?
        AND transactions.status = 'completed'
      GROUP BY productId
      ORDER BY qty DESC
      LIMIT ?
      ''',
      variables: [
        Variable.withDateTime(start),
        Variable.withDateTime(end),
        Variable.withInt(limit),
      ],
      readsFrom: {transactionItems, transactions},
    );

    final rows = await query.get();
    return rows.map((row) {
      return TopProductResult(
        productId: row.read<String>('productId'),
        quantitySold: row.read<double>('qty'),
        totalRevenue: row.read<double>('rev'),
      );
    }).toList();
  }

  /// Voids an existing transaction by [id].
  ///
  /// This operation:
  /// 1. Updates transaction status to 'voided'.
  /// 2. Reverses the stock levels for all items in the transaction.
  /// 3. Records 'return' inventory log entries.
  /// 4. Marks as unsynced to trigger server-side voiding if applicable.
  Future<void> voidTransaction(String id, String staffId) async {
    return db.transaction(() async {
      await (update(transactions)..where((t) => t.id.equals(id))).write(
          const TransactionsCompanion(
              status: Value('voided'), isSynced: Value(false),),);

      final items = await (select(transactionItems)
            ..where((t) => t.transactionId.equals(id)))
          .get();
      for (final item in items) {
        // Reverse stock
        await customUpdate(
          'UPDATE products SET stock = stock + ? WHERE id = ?',
          variables: [
            Variable.withReal(item.quantity),
            Variable.withString(item.productId),
          ],
          updates: {products},
        );

        final p = await (select(products)
              ..where((tbl) => tbl.id.equals(item.productId)))
            .getSingle();
        // Insert log
        await into(inventoryLogs).insert(
          InventoryLogsCompanion(
            id: Value(_uuid.v4()),
            productId: Value(item.productId),
            changeAmount: Value(item.quantity),
            stockBefore: Value(p.stock - item.quantity),
            stockAfter: Value(p.stock),
            reason: const Value('return'),
            referenceId: Value(id),
            staffId: Value(staffId),
          ),
        );
      }
    });
  }

  /// Returns a reactive stream of transactions that have not yet been synced.
  Stream<List<TransactionModel>> watchUnsyncedTransactions() {
    return (select(transactions)..where((tbl) => tbl.isSynced.equals(false)))
        .watch();
  }
}
