import 'package:equatable/equatable.dart';
import 'package:khmerbiz_pos/domain/entities/product.dart';

/// Data model for top-selling products in analytics.
class TopProduct extends Equatable {
  /// Creates a [TopProduct] summary.
  const TopProduct({
    required this.product,
    required this.quantitySold,
    required this.totalRevenue,
  });

  /// The product entity.
  final Product product;

  /// Total quantity of this product sold in the period.
  final double quantitySold;

  /// Total revenue generated by this product (in KHR).
  final double totalRevenue;

  @override
  List<Object?> get props => [
        product,
        quantitySold,
        totalRevenue,
      ];
}
